/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathsmate;

import java.awt.CardLayout;
import java.awt.LayoutManager;
import java.util.ArrayList;

/**
 *
 * @author Ian Donnelly X14111659
 */
public class AlgebraFormula extends javax.swing.JPanel {
    
    private ArrayList<AlgebraFormulaStorage> AForm;
    AlgebraFormulaStorage AF1 = new AlgebraFormulaStorage("Multiplying Powers", "Multiplying powers with the same base:", 
            "x^a . x^b = x^a+b", "Raising a power to a power:", "(x^a)^b = x^ab", 
            "Power of a product property:", "xy^a = x^a.y^a", 
            "Difference of two squares:", "(x+y)(y-x) = x^2 - y^2");
    AlgebraFormulaStorage AF2 = new AlgebraFormulaStorage("Multiplying Polynomials","First terms:", "(2x + 3)(x - 2) = 2x(x) = 2x^2", 
            "Outer terms:", "(2x + 3)(x - 2) = 2x(-2) = -4x", 
            "Inside terms:", "(2x + 3)(x - 2) = 3(x) = 3x", 
            "Last terms:", "(2x + 3)(x - 2) = 3(-2) = -6");
    AlgebraFormulaStorage AF3 = new AlgebraFormulaStorage("Squares and Cubes","Difference of Two Squares:", "(x+y)(x-y) = x^2 - y^2", 
            "Difference of Two Squares:", "y^2 - x^2 = (x+y)(x-y)", 
            "Sum of two cubes:", "x^3 + y^3 = (x-y)(x^2 - xy + y^2)", 
            "Difference of two cubes:", "x^3 - y^3 = (x-y)(x^2 + xy + y)");
    AlgebraFormulaStorage AF4 = new AlgebraFormulaStorage("Multiplying Powers","Thanks Aaron", "x^a . x^b = x^a+b", 
            "Raising a power to a power:", "(x^a)^b = x^ab", 
            "Power of a product property:", "xy^a = x^a.y^a", 
            "Difference of two squares:", "(x+y)(y-x) = x^2 - y^2");
    AlgebraFormulaStorage AF5 = new AlgebraFormulaStorage("Multiplying Powers","Hello World", "x^a . x^b = x^a+b", 
            "Raising a power to a power:", "(x^a)^b = x^ab", 
            "Power of a product property:", "xy^a = x^a.y^a", 
            "Difference of two squares:", "(x+y)(y-x) = x^2 - y^2");
    
    private int count;

    /**
     * Creates new form AlgebraMenu
     */
    public AlgebraFormula() {
        initComponents();
        AForm = new ArrayList<>();
        AForm.add(AF1);        
        AForm.add(AF2); 
        AForm.add(AF3);
        AForm.add(AF4);
        AForm.add(AF5);
        count = 0; 
    }

    //private AlgebraFormula(String multiplying_powers_with_the_same_base, String xa__xb__xab, String raising_a_power_to_a_power, String xab__xab, String power_of_a_product_property, String xya__xaya, String difference_of_two_squares, String xyyx__x2__y2) {
   
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subjectGroup1 = new javax.swing.ButtonGroup();
        subjectGroup2 = new javax.swing.ButtonGroup();
        subjectGroup3 = new javax.swing.ButtonGroup();
        subjectGroup4 = new javax.swing.ButtonGroup();
        subjectGroup5 = new javax.swing.ButtonGroup();
        subjectGroup6 = new javax.swing.ButtonGroup();
        mainMenuPanel = new javax.swing.JPanel();
        copyrightLbl = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        screenTitleLbl = new javax.swing.JLabel();
        nameBg = new javax.swing.JLabel();
        formula1JP = new javax.swing.JPanel();
        title1JL = new javax.swing.JLabel();
        formula1JL = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        title2JL = new javax.swing.JLabel();
        formula2JL = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        title3JL = new javax.swing.JLabel();
        formula3JL = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        title4JL = new javax.swing.JLabel();
        formula4JL = new javax.swing.JLabel();
        pageTitleJL = new javax.swing.JLabel();
        nextBtn = new javax.swing.JButton();
        previousBtn = new javax.swing.JButton();

        mainMenuPanel.setBackground(new java.awt.Color(52, 152, 219));
        mainMenuPanel.setPreferredSize(new java.awt.Dimension(400, 640));
        mainMenuPanel.setLayout(null);

        copyrightLbl.setBackground(new java.awt.Color(255, 255, 255));
        copyrightLbl.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        copyrightLbl.setForeground(new java.awt.Color(255, 255, 255));
        copyrightLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyrightLbl.setText("Copyright © 2015 | Maths Mate");
        copyrightLbl.setAlignmentY(0.0F);
        mainMenuPanel.add(copyrightLbl);
        copyrightLbl.setBounds(30, 580, 340, 30);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsmate/homeIcon.png"))); // NOI18N
        homeBtn.setAlignmentY(0.0F);
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.setMaximumSize(new java.awt.Dimension(100, 100));
        homeBtn.setMinimumSize(new java.awt.Dimension(100, 100));
        homeBtn.setPreferredSize(new java.awt.Dimension(100, 100));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        mainMenuPanel.add(homeBtn);
        homeBtn.setBounds(300, 10, 80, 50);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsmate/backIcon.png"))); // NOI18N
        backBtn.setAlignmentY(0.0F);
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.setMaximumSize(new java.awt.Dimension(100, 100));
        backBtn.setMinimumSize(new java.awt.Dimension(100, 100));
        backBtn.setPreferredSize(new java.awt.Dimension(100, 100));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        mainMenuPanel.add(backBtn);
        backBtn.setBounds(20, 10, 80, 50);

        screenTitleLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        screenTitleLbl.setForeground(new java.awt.Color(255, 255, 255));
        screenTitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        screenTitleLbl.setText("Algebra Formula");
        mainMenuPanel.add(screenTitleLbl);
        screenTitleLbl.setBounds(110, 10, 180, 50);

        nameBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsmate/nameIcon.png"))); // NOI18N
        nameBg.setText("hello");
        mainMenuPanel.add(nameBg);
        nameBg.setBounds(90, 10, 220, 50);

        formula1JP.setBackground(new java.awt.Color(142, 68, 173));
        formula1JP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        title1JL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title1JL.setForeground(new java.awt.Color(255, 255, 255));
        title1JL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1JL.setText("Multiplying powers with the same base:");
        title1JL.setPreferredSize(new java.awt.Dimension(270, 17));

        formula1JL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        formula1JL.setForeground(new java.awt.Color(255, 255, 255));
        formula1JL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formula1JL.setText("x^a . x^b = x^a+b");

        title2JL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title2JL.setForeground(new java.awt.Color(255, 255, 255));
        title2JL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title2JL.setText("Raising a power to a power:");

        formula2JL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        formula2JL.setForeground(new java.awt.Color(255, 255, 255));
        formula2JL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formula2JL.setText("(x^a)^b = x^ab");

        title3JL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title3JL.setForeground(new java.awt.Color(255, 255, 255));
        title3JL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title3JL.setText("Power of a product property:");

        formula3JL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        formula3JL.setForeground(new java.awt.Color(255, 255, 255));
        formula3JL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formula3JL.setText("xy^a = x^a.y^a");

        title4JL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title4JL.setForeground(new java.awt.Color(255, 255, 255));
        title4JL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title4JL.setText("Difference of two squares:");

        formula4JL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        formula4JL.setForeground(new java.awt.Color(255, 255, 255));
        formula4JL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formula4JL.setText("(x+y)(y-x) = x^2 - y^2");

        pageTitleJL.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        pageTitleJL.setForeground(new java.awt.Color(255, 255, 255));
        pageTitleJL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pageTitleJL.setText("Multiplying Powers");

        javax.swing.GroupLayout formula1JPLayout = new javax.swing.GroupLayout(formula1JP);
        formula1JP.setLayout(formula1JPLayout);
        formula1JPLayout.setHorizontalGroup(
            formula1JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formula1JPLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(formula1JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pageTitleJL, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title4JL, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(formula1JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(formula2JL, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                        .addComponent(title1JL, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                        .addComponent(formula1JL, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                        .addComponent(jSeparator1)
                        .addComponent(title2JL, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                        .addComponent(jSeparator2)
                        .addComponent(title3JL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(formula3JL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3))
                    .addComponent(formula4JL, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        formula1JPLayout.setVerticalGroup(
            formula1JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formula1JPLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(pageTitleJL, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(title1JL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formula1JL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(title2JL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formula2JL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(title3JL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formula3JL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(title4JL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formula4JL, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainMenuPanel.add(formula1JP);
        formula1JP.setBounds(20, 80, 360, 420);

        nextBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        mainMenuPanel.add(nextBtn);
        nextBtn.setBounds(260, 520, 89, 40);

        previousBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        previousBtn.setText("Previous");
        previousBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousBtnActionPerformed(evt);
            }
        });
        mainMenuPanel.add(previousBtn);
        previousBtn.setBounds(50, 520, 120, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "ALGEBRA_MENU");
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "MAIN");
        }
    }//GEN-LAST:event_homeBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
        nextFormula();
    }//GEN-LAST:event_nextBtnActionPerformed
/* GitHub caused an error here - disregard code
    private void previousBtnActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        previousFormula();
    }                                           
*/
    private void previousBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousBtnActionPerformed
        // TODO add your handling code here:
        previousFormula();
    }//GEN-LAST:event_previousBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel copyrightLbl;
    private javax.swing.JLabel formula1JL;
    private javax.swing.JPanel formula1JP;
    private javax.swing.JLabel formula2JL;
    private javax.swing.JLabel formula3JL;
    private javax.swing.JLabel formula4JL;
    private javax.swing.JButton homeBtn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JLabel nameBg;
    private javax.swing.JButton nextBtn;
    private javax.swing.JLabel pageTitleJL;
    private javax.swing.JButton previousBtn;
    private javax.swing.JLabel screenTitleLbl;
    private javax.swing.ButtonGroup subjectGroup1;
    private javax.swing.ButtonGroup subjectGroup2;
    private javax.swing.ButtonGroup subjectGroup3;
    private javax.swing.ButtonGroup subjectGroup4;
    private javax.swing.ButtonGroup subjectGroup5;
    private javax.swing.ButtonGroup subjectGroup6;
    private javax.swing.JLabel title1JL;
    private javax.swing.JLabel title2JL;
    private javax.swing.JLabel title3JL;
    private javax.swing.JLabel title4JL;
    // End of variables declaration//GEN-END:variables

    private void nextFormula() {
        if(count + 1 >= AForm.size()){
            count = 0;
        }else{
            count++;
        }
        pageTitleJL.setText(AForm.get(count).getPageTitle());
        title1JL.setText(AForm.get(count).getTitle1());
        title2JL.setText(AForm.get(count).getTitle2());
        title3JL.setText(AForm.get(count).getTitle3());
        title4JL.setText(AForm.get(count).getTitle4());
        formula1JL.setText(AForm.get(count).getFormula1());
        formula2JL.setText(AForm.get(count).getFormula2());
        formula3JL.setText(AForm.get(count).getFormula3());
        formula4JL.setText(AForm.get(count).getFormula4());
        
    }
    
    private void previousFormula(){
        if(count - 1 < 0){
            count = AForm.size() - 1;
        }else{
            count--;
        }
        pageTitleJL.setText(AForm.get(count).getPageTitle());
        title1JL.setText(AForm.get(count).getTitle1());
        title2JL.setText(AForm.get(count).getTitle2());
        title3JL.setText(AForm.get(count).getTitle3());
        title4JL.setText(AForm.get(count).getTitle4());
        formula1JL.setText(AForm.get(count).getFormula1());
        formula2JL.setText(AForm.get(count).getFormula2());
        formula3JL.setText(AForm.get(count).getFormula3());
        formula4JL.setText(AForm.get(count).getFormula4());
    }
}
