/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathsmate;

import java.awt.CardLayout;
import java.awt.LayoutManager;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Ian Donnelly X14111659
 */
public class AlgebraFormulaAdmin extends javax.swing.JPanel {

    private ArrayList<AlgebraFormulaStorage> AFormAd;
    private ArrayList<AlgebraFormulaStorage> AFormSave;
    AlgebraFormulaStorage AFA1 = new AlgebraFormulaStorage("Multiplying Powers", "Multiplying powers with the same base:",
            "x^a . x^b = x^a+b", "Raising a power to a power:", "(x^a)^b = x^ab",
            "Power of a product property:", "xy^a = x^a.y^a",
            "Difference of two squares:", "(x+y)(y-x) = x^2 - y^2");
    AlgebraFormulaStorage AFA2 = new AlgebraFormulaStorage("<html>Multiplying Polynomials (<font color=\"#6699FF\">FOIL</font>)</html>",
            "<html><font color=\"#6699FF\">F</font>irst terms:</html>", "<html>(<font color=\"yellow\">2x </font> + 3)(<font color=\"yellow\">x</font> - 2) = 2x(x) = <font color=\"yellow\">2x^2</font></html>",
            "<html><font color=\"#6699FF\">O</font>uter terms:</html>", "<html>(<font color=\"yellow\">2x </font> + 3)(x <font color=\"yellow\">- 2</font>) = 2x(-2) = <font color=\"yellow\">-4x</font></html>",
            "<html><font color=\"#6699FF\">I</font>nside terms:</html>", "<html>(2x <font color=\"yellow\">+ 3</font>)(<font color=\"yellow\">x</font> - 2) = 3(x) = <font color=\"yellow\">3x</font></html>",
            "<html><font color=\"#6699FF\">L</font>ast terms:</html>", "<html>(2x <font color=\"yellow\">+ 3</font>)(x <font color=\"yellow\">- 2</font>) = 3(-2) = <font color=\"yellow\">-6</font></html>");
    AlgebraFormulaStorage AFA3 = new AlgebraFormulaStorage("Squares and Cubes", "Difference of Two Squares:", "(x+y)(x-y) = x^2 - y^2",
            "Difference of Two Squares:", "y^2 - x^2 = (x+y)(x-y)",
            "Sum of two cubes:", "x^3 + y^3 = (x-y)(x^2 - xy + y^2)",
            "Difference of two cubes:", "x^3 - y^3 = (x-y)(x^2 + xy + y)");
    AlgebraFormulaStorage AFA4 = new AlgebraFormulaStorage("Calculus", "Chain Rule:", "dy/dx = (dy/du)(du/dx)",
            "Derivative of the inverse:", "dy/dx = 1/dx/dy",
            "Power Rule:", "d/dx(x^n) = nx^n-1",
            "Product Rule:", "(fg)' = f'g + fg'");
    AlgebraFormulaStorage AFA5 = new AlgebraFormulaStorage("Linear Algebra", "Associativity", "(x + y) + z = x + (y + z)",
            "Zero and unity:", "x + 0 = x = 0 + x",
            "Distributivity:", "(x + y)*z = x*z + y*z",
            "Commutativity:", "x + y = Y + x");

    private int count;

    /**
     * Creates new form AlgebraMenu
     */
    public AlgebraFormulaAdmin() {
        initComponents();
        AFormAd = new ArrayList<>();
        AFormAd.add(AFA1);
        AFormAd.add(AFA2);
        AFormAd.add(AFA3);
        AFormAd.add(AFA4);
        AFormAd.add(AFA5);
        count = 0;

        try {
            FileInputStream fIS = new FileInputStream("algFormSave.data");
            ObjectInputStream oIS = new ObjectInputStream(fIS);
            AFormSave = (ArrayList<AlgebraFormulaStorage>) oIS.readObject();
            pageTitleField.setText(AFormSave.get(count).getPageTitle());
            title1Field.setText(AFormSave.get(count).getTitle1());
            formula1Field.setText(AFormSave.get(count).getFormula1());
            title2Field.setText(AFormSave.get(count).getTitle2());
            formula2Field.setText(AFormSave.get(count).getFormula2());
            title3Field.setText(AFormSave.get(count).getTitle3());
            formula3Field.setText(AFormSave.get(count).getFormula3());
            title4Field.setText(AFormSave.get(count).getTitle4());
            formula4Field.setText(AFormSave.get(count).getFormula4());
            fIS.close();
            oIS.close();
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Error: File not found");
        } catch (IOException | ClassNotFoundException f) {
            JOptionPane.showMessageDialog(null, "Error: Class not found!");
        }

    }
    //}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subjectGroup1 = new javax.swing.ButtonGroup();
        subjectGroup2 = new javax.swing.ButtonGroup();
        subjectGroup3 = new javax.swing.ButtonGroup();
        subjectGroup4 = new javax.swing.ButtonGroup();
        subjectGroup5 = new javax.swing.ButtonGroup();
        subjectGroup6 = new javax.swing.ButtonGroup();
        mainMenuPanel = new javax.swing.JPanel();
        copyrightLbl = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        screenTitleLbl = new javax.swing.JLabel();
        nameBg = new javax.swing.JLabel();
        formula1JP = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        pageTitleField = new javax.swing.JTextField();
        title1Field = new javax.swing.JTextField();
        formula1Field = new javax.swing.JTextField();
        title2Field = new javax.swing.JTextField();
        formula2Field = new javax.swing.JTextField();
        title3Field = new javax.swing.JTextField();
        formula3Field = new javax.swing.JTextField();
        title4Field = new javax.swing.JTextField();
        formula4Field = new javax.swing.JTextField();
        nextBtn = new javax.swing.JButton();
        previousBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();

        mainMenuPanel.setBackground(new java.awt.Color(52, 152, 219));
        mainMenuPanel.setPreferredSize(new java.awt.Dimension(400, 640));
        mainMenuPanel.setLayout(null);

        copyrightLbl.setBackground(new java.awt.Color(255, 255, 255));
        copyrightLbl.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        copyrightLbl.setForeground(new java.awt.Color(255, 255, 255));
        copyrightLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyrightLbl.setText("Copyright © 2015 | Maths Mate");
        copyrightLbl.setAlignmentY(0.0F);
        mainMenuPanel.add(copyrightLbl);
        copyrightLbl.setBounds(30, 580, 340, 30);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsmate/homeIcon.png"))); // NOI18N
        homeBtn.setAlignmentY(0.0F);
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.setMaximumSize(new java.awt.Dimension(100, 100));
        homeBtn.setMinimumSize(new java.awt.Dimension(100, 100));
        homeBtn.setPreferredSize(new java.awt.Dimension(100, 100));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        mainMenuPanel.add(homeBtn);
        homeBtn.setBounds(300, 10, 80, 50);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsmate/backIcon.png"))); // NOI18N
        backBtn.setAlignmentY(0.0F);
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.setMaximumSize(new java.awt.Dimension(100, 100));
        backBtn.setMinimumSize(new java.awt.Dimension(100, 100));
        backBtn.setPreferredSize(new java.awt.Dimension(100, 100));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        mainMenuPanel.add(backBtn);
        backBtn.setBounds(20, 10, 80, 50);

        screenTitleLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        screenTitleLbl.setForeground(new java.awt.Color(255, 255, 255));
        screenTitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        screenTitleLbl.setText("AF Admin");
        mainMenuPanel.add(screenTitleLbl);
        screenTitleLbl.setBounds(110, 10, 180, 50);

        nameBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsmate/nameIcon.png"))); // NOI18N
        nameBg.setText("hello");
        mainMenuPanel.add(nameBg);
        nameBg.setBounds(90, 10, 220, 50);

        formula1JP.setBackground(new java.awt.Color(142, 68, 173));
        formula1JP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        pageTitleField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout formula1JPLayout = new javax.swing.GroupLayout(formula1JP);
        formula1JP.setLayout(formula1JPLayout);
        formula1JPLayout.setHorizontalGroup(
            formula1JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formula1JPLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(formula1JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pageTitleField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title1Field, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formula1Field)
                    .addComponent(title2Field)
                    .addComponent(formula2Field)
                    .addComponent(title3Field)
                    .addComponent(formula3Field)
                    .addComponent(title4Field)
                    .addComponent(formula4Field, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        formula1JPLayout.setVerticalGroup(
            formula1JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formula1JPLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(pageTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(title1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formula1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(title2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formula2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(title3Field, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(formula3Field, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(title4Field, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formula4Field, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        mainMenuPanel.add(formula1JP);
        formula1JP.setBounds(20, 80, 360, 420);

        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        mainMenuPanel.add(nextBtn);
        nextBtn.setBounds(260, 540, 100, 20);

        previousBtn.setText("Previous");
        previousBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousBtnActionPerformed(evt);
            }
        });
        mainMenuPanel.add(previousBtn);
        previousBtn.setBounds(40, 540, 100, 20);

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        mainMenuPanel.add(saveBtn);
        saveBtn.setBounds(150, 530, 100, 20);

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        mainMenuPanel.add(deleteBtn);
        deleteBtn.setBounds(260, 510, 100, 20);

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        mainMenuPanel.add(addBtn);
        addBtn.setBounds(40, 510, 100, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "ALGEBRA_FORMULA");
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout) layout;
            cl.show(getParent(), "MAIN");
        }
    }//GEN-LAST:event_homeBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
        nextFormula();
    }//GEN-LAST:event_nextBtnActionPerformed
    /* GitHub caused an error here - disregard code
     private void previousBtnActionPerformed(java.awt.event.ActionEvent evt) {                                            
     // TODO add your handling code here:
     previousFormula();
     }                                           
     */
    private void previousBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousBtnActionPerformed
        // TODO add your handling code here:
        previousFormula();
    }//GEN-LAST:event_previousBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try {
            FileOutputStream fOut = new FileOutputStream("algFormSave.data");
            ObjectOutputStream oOut = new ObjectOutputStream(fOut);
            oOut.writeObject(AFormSave);
            fOut.close();
            oOut.close();
            JOptionPane.showMessageDialog(null, "File Saved Successfully!");
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "File Not Found!");
            System.out.println(e);
        } catch (IOException f) {
            JOptionPane.showMessageDialog(null, "IO Exception!");
            System.out.println(f);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String pageTitle = pageTitleField.getText();
        String title1 = title1Field.getText();
        String title2 = title2Field.getText();
        String title3 = title3Field.getText();
        String title4 = title4Field.getText();
        String formula1 = formula1Field.getText();
        String formula2 = formula2Field.getText();
        String formula3 = formula3Field.getText();
        String formula4 = formula4Field.getText();
        AlgebraFormulaStorage algStor = new AlgebraFormulaStorage(pageTitle, title1, formula1, title2, formula2, title3, formula3, title4, formula4);
        AFormSave.add(algStor);
        count++;
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        try {
            AFormSave.remove(count);
            count--;
            pageTitleField.setText(AFormSave.get(count).getPageTitle());
            title1Field.setText(AFormSave.get(count).getTitle1());
            formula1Field.setText(AFormSave.get(count).getFormula1());
            title2Field.setText(AFormSave.get(count).getTitle2());
            formula2Field.setText(AFormSave.get(count).getFormula2());
            title3Field.setText(AFormSave.get(count).getTitle3());
            formula3Field.setText(AFormSave.get(count).getFormula3());
            title4Field.setText(AFormSave.get(count).getTitle4());
            formula4Field.setText(AFormSave.get(count).getFormula4());
        } catch (IndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Can not delete unadded record");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel copyrightLbl;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField formula1Field;
    private javax.swing.JPanel formula1JP;
    private javax.swing.JTextField formula2Field;
    private javax.swing.JTextField formula3Field;
    private javax.swing.JTextField formula4Field;
    private javax.swing.JButton homeBtn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JLabel nameBg;
    private javax.swing.JButton nextBtn;
    private javax.swing.JTextField pageTitleField;
    private javax.swing.JButton previousBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel screenTitleLbl;
    private javax.swing.ButtonGroup subjectGroup1;
    private javax.swing.ButtonGroup subjectGroup2;
    private javax.swing.ButtonGroup subjectGroup3;
    private javax.swing.ButtonGroup subjectGroup4;
    private javax.swing.ButtonGroup subjectGroup5;
    private javax.swing.ButtonGroup subjectGroup6;
    private javax.swing.JTextField title1Field;
    private javax.swing.JTextField title2Field;
    private javax.swing.JTextField title3Field;
    private javax.swing.JTextField title4Field;
    // End of variables declaration//GEN-END:variables

    private void nextFormula() {
        if (count + 1 < AFormSave.size()) {
            count++;
            pageTitleField.setText(AFormSave.get(count).getPageTitle());
            title1Field.setText(AFormSave.get(count).getTitle1());
            formula1Field.setText(AFormSave.get(count).getFormula1());
            title2Field.setText(AFormSave.get(count).getTitle2());
            formula2Field.setText(AFormSave.get(count).getFormula2());
            title3Field.setText(AFormSave.get(count).getTitle3());
            formula3Field.setText(AFormSave.get(count).getFormula3());
            title4Field.setText(AFormSave.get(count).getTitle4());
            formula4Field.setText(AFormSave.get(count).getFormula4());
        } else {
            pageTitleField.setText("");
            title1Field.setText("");
            formula1Field.setText("");
            title2Field.setText("");
            formula2Field.setText("");
            title3Field.setText("");
            formula3Field.setText("");
            title4Field.setText("");
            formula4Field.setText("");
            count = AFormSave.size();
        }
    }

    private void previousFormula() {
        if (count - 1 < 0) {
            count = AFormSave.size() - 1;
        } else {
            count--;
        }
        pageTitleField.setText(AFormSave.get(count).getPageTitle());
        title1Field.setText(AFormSave.get(count).getTitle1());
        formula1Field.setText(AFormSave.get(count).getFormula1());
        title2Field.setText(AFormSave.get(count).getTitle2());
        formula2Field.setText(AFormSave.get(count).getFormula2());
        title3Field.setText(AFormSave.get(count).getTitle3());
        formula3Field.setText(AFormSave.get(count).getFormula3());
        title4Field.setText(AFormSave.get(count).getTitle4());
        formula4Field.setText(AFormSave.get(count).getFormula4());
    }
}
