/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathsmate;

import java.awt.Desktop;
import java.net.URL;

/**
 *
 * @author Aaron
 */
public class CoursePanel extends javax.swing.JPanel{

    /**
     * Creates new form CoursePanel
     */
    public CoursePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        course1 = new javax.swing.JPanel();
        courseCollege2 = new javax.swing.JLabel();
        addressLbl2 = new javax.swing.JLabel();
        levelLbl = new javax.swing.JLabel();
        yearLbl = new javax.swing.JLabel();
        pointsLbl2 = new javax.swing.JLabel();
        costLbl = new javax.swing.JLabel();

        course1.setBackground(new java.awt.Color(142, 68, 173));
        course1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        course1.setMaximumSize(new java.awt.Dimension(340, 100));
        course1.setMinimumSize(new java.awt.Dimension(340, 100));
        course1.setPreferredSize(new java.awt.Dimension(400, 100));
        course1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                course1MouseClicked(evt);
            }
        });

        courseCollege2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        courseCollege2.setForeground(new java.awt.Color(255, 255, 255));
        courseCollege2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        courseCollege2.setText("NCI");

        addressLbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addressLbl2.setForeground(new java.awt.Color(255, 255, 255));
        addressLbl2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addressLbl2.setText("IFSC, Dublin");

        levelLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        levelLbl.setForeground(new java.awt.Color(255, 255, 255));
        levelLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        levelLbl.setText("Level: 8");

        yearLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        yearLbl.setForeground(new java.awt.Color(255, 255, 255));
        yearLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        yearLbl.setText("4 Years");

        pointsLbl2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pointsLbl2.setForeground(new java.awt.Color(255, 255, 255));
        pointsLbl2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pointsLbl2.setText("405 Points");

        costLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        costLbl.setForeground(new java.awt.Color(255, 255, 255));
        costLbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        costLbl.setText("Price: €2500");

        javax.swing.GroupLayout course1Layout = new javax.swing.GroupLayout(course1);
        course1.setLayout(course1Layout);
        course1Layout.setHorizontalGroup(
            course1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(course1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(course1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(course1Layout.createSequentialGroup()
                        .addComponent(costLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pointsLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                    .addGroup(course1Layout.createSequentialGroup()
                        .addGroup(course1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(courseCollege2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addressLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(course1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yearLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(levelLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(57, 57, 57))
        );
        course1Layout.setVerticalGroup(
            course1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(course1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(course1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseCollege2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(levelLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(course1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(course1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(course1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pointsLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, course1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(costLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(course1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(course1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    String url;
    
    private void course1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_course1MouseClicked
        try {
            Desktop.getDesktop().browse(new URL("http://www." + url).toURI());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_course1MouseClicked

    @Override
    public void setName(String name){
        courseCollege2.setText(name);
    }
    
    public void setLevel(int level){
        levelLbl.setText("Level: " + Integer.toString(level));
    }
    
    public void setYears(int years){
        yearLbl.setText(Integer.toString(years) + " Years");
    }
    
    public void setPoints(int points){
        pointsLbl2.setText(Integer.toString(points) + " Points");
    }
    
    public void setAddress(String address){
        addressLbl2.setText(address); 
    }
    
    public void setURL(String url){
        this.url = url;
    }
    
    public void setPrice(int price){
        costLbl.setText("Price: €" + Integer.toString(price));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLbl2;
    private javax.swing.JLabel costLbl;
    private javax.swing.JPanel course1;
    private javax.swing.JLabel courseCollege2;
    private javax.swing.JLabel levelLbl;
    private javax.swing.JLabel pointsLbl2;
    private javax.swing.JLabel yearLbl;
    // End of variables declaration//GEN-END:variables
}
