/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathsmate;

import java.awt.CardLayout;
import java.awt.LayoutManager;

/**
 *
 * @author Aaron
 */
public class MainMenu extends javax.swing.JPanel {

    /**
     * Creates new form MainMenuPanel
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainMenuPanel = new javax.swing.JPanel();
        copyrightLbl = new javax.swing.JLabel();
        algebraBtn = new javax.swing.JButton();
        trigBtn = new javax.swing.JButton();
        extrasBtn = new javax.swing.JButton();
        geometryBtn = new javax.swing.JButton();
        titleLbl = new javax.swing.JLabel();

        mainMenuPanel.setBackground(new java.awt.Color(52, 152, 219));
        mainMenuPanel.setPreferredSize(new java.awt.Dimension(400, 640));
        mainMenuPanel.setLayout(null);

        copyrightLbl.setBackground(new java.awt.Color(255, 255, 255));
        copyrightLbl.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        copyrightLbl.setForeground(new java.awt.Color(255, 255, 255));
        copyrightLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyrightLbl.setText("Copyright © 2015 | Maths Mate");
        copyrightLbl.setAlignmentY(0.0F);
        mainMenuPanel.add(copyrightLbl);
        copyrightLbl.setBounds(30, 580, 340, 30);

        algebraBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsmate/algebraIcon.png"))); // NOI18N
        algebraBtn.setAlignmentY(0.0F);
        algebraBtn.setBorderPainted(false);
        algebraBtn.setContentAreaFilled(false);
        algebraBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        algebraBtn.setMaximumSize(new java.awt.Dimension(100, 100));
        algebraBtn.setMinimumSize(new java.awt.Dimension(100, 100));
        algebraBtn.setPreferredSize(new java.awt.Dimension(100, 100));
        algebraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algebraBtnActionPerformed(evt);
            }
        });
        mainMenuPanel.add(algebraBtn);
        algebraBtn.setBounds(50, 150, 100, 130);

        trigBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsmate/trigIcon.png"))); // NOI18N
        trigBtn.setAlignmentY(0.0F);
        trigBtn.setBorderPainted(false);
        trigBtn.setContentAreaFilled(false);
        trigBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        trigBtn.setMaximumSize(new java.awt.Dimension(100, 100));
        trigBtn.setMinimumSize(new java.awt.Dimension(100, 100));
        trigBtn.setPreferredSize(new java.awt.Dimension(100, 100));
        trigBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trigBtnActionPerformed(evt);
            }
        });
        mainMenuPanel.add(trigBtn);
        trigBtn.setBounds(260, 150, 100, 130);

        extrasBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsmate/extraIcon.png"))); // NOI18N
        extrasBtn.setAlignmentY(0.0F);
        extrasBtn.setBorderPainted(false);
        extrasBtn.setContentAreaFilled(false);
        extrasBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        extrasBtn.setMaximumSize(new java.awt.Dimension(100, 100));
        extrasBtn.setMinimumSize(new java.awt.Dimension(100, 100));
        extrasBtn.setPreferredSize(new java.awt.Dimension(100, 100));
        extrasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extrasBtnActionPerformed(evt);
            }
        });
        mainMenuPanel.add(extrasBtn);
        extrasBtn.setBounds(260, 360, 100, 130);

        geometryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsmate/geomIcon.png"))); // NOI18N
        geometryBtn.setAlignmentY(0.0F);
        geometryBtn.setBorderPainted(false);
        geometryBtn.setContentAreaFilled(false);
        geometryBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        geometryBtn.setMaximumSize(new java.awt.Dimension(100, 100));
        geometryBtn.setMinimumSize(new java.awt.Dimension(100, 100));
        geometryBtn.setPreferredSize(new java.awt.Dimension(100, 100));
        geometryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geometryBtnActionPerformed(evt);
            }
        });
        mainMenuPanel.add(geometryBtn);
        geometryBtn.setBounds(50, 360, 100, 130);

        titleLbl.setBackground(new java.awt.Color(255, 255, 255));
        titleLbl.setFont(new java.awt.Font("Calibri Light", 0, 60)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(255, 255, 255));
        titleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLbl.setText("Maths Mate");
        titleLbl.setAlignmentY(0.0F);
        mainMenuPanel.add(titleLbl);
        titleLbl.setBounds(50, 30, 307, 74);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void algebraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_algebraBtnActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "ALGEBRA_MENU");
        }
    }//GEN-LAST:event_algebraBtnActionPerformed

    private void trigBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trigBtnActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "TRIG_MENU");
        }
    }//GEN-LAST:event_trigBtnActionPerformed

    private void extrasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extrasBtnActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "EXTRAS_MENU");
        }
    }//GEN-LAST:event_extrasBtnActionPerformed

    private void geometryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geometryBtnActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "GEOMETRY_MENU");
        }
    }//GEN-LAST:event_geometryBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton algebraBtn;
    private javax.swing.JLabel copyrightLbl;
    private javax.swing.JButton extrasBtn;
    private javax.swing.JButton geometryBtn;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JButton trigBtn;
    // End of variables declaration//GEN-END:variables
}
