/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathsmate;

import java.awt.CardLayout;
import java.awt.LayoutManager;
import java.util.ArrayList;

/**
 *
 * @author Elmo
 */
public class NotesAlgerbra extends javax.swing.JPanel {

    /**
     * Creates new form AlgebraMenu
     */
     int count;
    ArrayList<Notes> n = new ArrayList<>();
    Notes n1 = new Notes(" BOMDAS (order of operations\nBrackets First\n(Powers,Roots) before Multiply,Divide, add or subtract\n Multiply or Divide before you add or subtract\n otherwise just go left to right\n B \nBrackets first\n O \n Orders (ie Powers and Square Roots, etc.)\n DM \n Division and Multiplication (left-to-right)\n AS \n Addition and Subtraction (left-to-right)\n");//Page 1
    Notes n2 = new Notes("Quadratic Equation\n Example: Solve 5x² + 2x + 1 = 0\nCoefficients are:\n a = 5, b = 2, c = 1 \n Note that The Discriminant is negative: \n b2 - 4ac = 22 - 4×5×1 = -16 \n Use the Quadratic Formula:\n x = [ -2 ± v(-16) ] / 10 \n The square root of -16 is 4i\n (i is v-1, read Imaginary Numbers to find out more)\n So: x=(-2± 4i )/10\n Answer: x = -0.2 ± 0.4i\n");//Page 2
    Notes n3 = new Notes("Sequences\n When the sequence goes on forever it is called an infinite sequence,\notherwise it is a finite sequence\nExamples\n{1, 2, 3, 4, ...} is a very simple sequence (and it is an infinite sequence)\n{20, 25, 30, 35, ...} is also an infinite sequence\n {1, 3, 5, 7} is the sequence of the first 4 odd numbers (and is a finite sequence)\n{4, 3, 2, 1} is 4 to 1 backwards\n{1, 2, 4, 8, 16, 32, ...} is an infinite sequence where every term doubles\n{a, b, c, d, e} is the sequence of the first 5 letters alphabetically\n{f, r, e, d} is the sequence of letters in the name \"fred\"\n{0, 1, 0, 1, 0, 1, ...} is the sequence of alternating 0s and 1s (yes they are in order, it is an alternating order in this case)\n");//Page 3
    Notes n4 = new Notes("Dividing fractions\n To divide fractions, first \"flip\" the fraction we want to divide by, then use the same method as for multiplying:\nExample:\n3y2x+1  ÷  y2  =  3y2x+1  ×  2y\n  = (3y2)(2)(x+1)(y)\n= 6y2(x+1)(y)\n  =  6yx+1\n");//Page 4
    Notes n5 = new Notes("Summary \nQuadratic Equation in Standard Form: ax2 + bx + c = 0\nQuadratic Equations can be factored\nQuadratic Formula: x = [ -b ± v(b2-4ac) ] / 2a\nWhen the Discriminant (b2-4ac) is:\npositive, there are 2 real solutions\nzero, there is one real solution\nnegative, there are 2 complex solutions\nNotes Geometry\nCalculating Perimiter of a rectangle is 7+3+7+3 = 20\n");//Page 5
    public NotesAlgerbra() {
        initComponents();
         count = 0;
        n.add(n1);
        n.add(n2);
        n.add(n3);
        n.add(n4);
        n.add(n5);
        notesArea.setText(n.get(count).getNote());
           TrigimageStorage GF1 = new TrigimageStorage();
   TrigimageStorage GF2 = new TrigimageStorage("");
   TrigimageStorage GF2 = new TrigimageStorage("Q2 Algerbra notes.gif");
   TrigimageStorage GF2 = new TrigimageStorage("");
   TrigimageStorage GF2 = new TrigimageStorage("Q4 Algerbra notes.gif");
   TrigimageStorage GF2 = new TrigimageStorage("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        textField1 = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jTextField1 = new javax.swing.JTextField();
        textArea1 = new java.awt.TextArea();
        mainMenuPanel = new javax.swing.JPanel();
        copyrightLbl = new javax.swing.JLabel();
        homeBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        screenTitleLbl = new javax.swing.JLabel();
        nameBg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        notesArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        textField1.setText("textField1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsmate/Examples.fw.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jTextField1.setText("jTextField1");

        mainMenuPanel.setBackground(new java.awt.Color(52, 152, 219));
        mainMenuPanel.setPreferredSize(new java.awt.Dimension(400, 640));
        mainMenuPanel.setLayout(null);

        copyrightLbl.setBackground(new java.awt.Color(255, 255, 255));
        copyrightLbl.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        copyrightLbl.setForeground(new java.awt.Color(255, 255, 255));
        copyrightLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        copyrightLbl.setText("Copyright © 2015 | Maths Mate");
        copyrightLbl.setAlignmentY(0.0F);
        mainMenuPanel.add(copyrightLbl);
        copyrightLbl.setBounds(30, 580, 340, 30);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsmate/homeIcon.png"))); // NOI18N
        homeBtn.setAlignmentY(0.0F);
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.setMaximumSize(new java.awt.Dimension(100, 100));
        homeBtn.setMinimumSize(new java.awt.Dimension(100, 100));
        homeBtn.setPreferredSize(new java.awt.Dimension(100, 100));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        mainMenuPanel.add(homeBtn);
        homeBtn.setBounds(300, 10, 80, 50);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsmate/backIcon.png"))); // NOI18N
        backBtn.setAlignmentY(0.0F);
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.setMaximumSize(new java.awt.Dimension(100, 100));
        backBtn.setMinimumSize(new java.awt.Dimension(100, 100));
        backBtn.setPreferredSize(new java.awt.Dimension(100, 100));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        mainMenuPanel.add(backBtn);
        backBtn.setBounds(20, 10, 80, 50);

        screenTitleLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        screenTitleLbl.setForeground(new java.awt.Color(255, 255, 255));
        screenTitleLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        screenTitleLbl.setText("Algebra Notes");
        mainMenuPanel.add(screenTitleLbl);
        screenTitleLbl.setBounds(110, 10, 180, 50);

        nameBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsmate/nameIcon.png"))); // NOI18N
        nameBg.setText("hello");
        mainMenuPanel.add(nameBg);
        nameBg.setBounds(90, 10, 220, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mathsmate/algerbra Equation.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        mainMenuPanel.add(jLabel1);
        jLabel1.setBounds(50, 430, 300, 90);

        notesArea.setColumns(20);
        notesArea.setRows(5);
        notesArea.setText("Far far away, behind the word mountains,\n far from the countries Vokalia and Con\nsonantia, there live the blind texts. Se\nparated they live in Bookmarksgrove right at \nthe coast of the Semantics, a large languag\ne ocean. A small river named Duden flo\nws by their place and supplies it with t\nhe necessary regelialia. It is a paradisem\natic country, in which roasted parts\n of sentences fly into your mouth. Even t\\h\ne all-powerful Pointing has no control ab\nout the blind texts it is an almost unorth\nographic life One day however a small lin\ne of blind text by the name of Lorem Ips\num decided to leave for the far World of G\nrammar. The Big Oxmox advised her no\nt to do so, because there were thou\nsands of bad Commas, wild Question \nMarks and devious Semikoli, but the Li\nttle Blind Text didn’t listen. She pac\nked her seven versalia, put her initia\nl into the belt and \n\nma");
        jScrollPane3.setViewportView(notesArea);

        mainMenuPanel.add(jScrollPane3);
        jScrollPane3.setBounds(40, 70, 320, 340);

        jButton1.setText("Previous");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        mainMenuPanel.add(jButton1);
        jButton1.setBounds(20, 530, 73, 23);

        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        mainMenuPanel.add(jButton2);
        jButton2.setBounds(280, 530, 55, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainMenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "MAIN");
        }
    }//GEN-LAST:event_homeBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        LayoutManager layout = getParent().getLayout();
        if (layout instanceof CardLayout) {
            CardLayout cl = (CardLayout)layout;
            cl.show(getParent(), "ALGEBRA_MENU");
        }
    }//GEN-LAST:event_backBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     nextNote();        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   prevNote();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
      private void nextNote() {
        if(count + 1 >= n.size()){
            count = 0;
        } else {
            count++;
        }
        notesArea.setText(n.get(count).getNote());
    }
    
    private void prevNote() {
        if(count - 1 < 0){
            count = n.size() - 1;
        } else {
            count--;
        }
        notesArea.setText(n.get(count).getNote());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel copyrightLbl;
    private javax.swing.JButton homeBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel mainMenuPanel;
    private javax.swing.JLabel nameBg;
    private javax.swing.JTextArea notesArea;
    private javax.swing.JLabel screenTitleLbl;
    private java.awt.TextArea textArea1;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
